package com.swatt.blockchain.persistence;

public enum BlockColumns {
    BLOCKCHAIN_TICKER, HASH, TRANSACTION_COUNT, HEIGHT, DIFFICULTY, MERKLE_ROOT, TIMESTAMP, BITS, SIZE, VERSION_HEX, NONCE, PREV_HASH, NEXT_HASH, AVG_FEE, INDEXED, LARGEST_TX_HASH, LARGEST_TX_VALUE, LARGEST_TX_TIMESTAMP, TOTAL_SIZE, TOTAL_FEE, LARGEST_FEE, SMALLEST_FEE, FIRST_TX_TIMESTAMP, LAST_TX_TIMESTAMP
}
