package com.swatt.blockchain.persistence;

public enum BlockColumns {
    OFFSET, BLOCKCHAIN_TICKER, HASH, TRANSACTION_COUNT, HEIGHT, DIFFICULTY, MERKLE_ROOT, TIMESTAMP, BITS, SIZE, VERSION_HEX, NONCE, PREV_HASH, NEXT_HASH, AVG_FEE, LARGEST_TX_HASH, LARGEST_TX_AMOUNT, TOTAL_SIZE, TOTAL_FEE, LARGEST_FEE, SMALLEST_FEE, INDEXING_DURATION
}
